In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from wordcloud import WordCloud
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.naive_bayes import GaussianNB

[nltk_data] Error loading stopwords: <urlopen error [SSL:
[nltk_data]     CERTIFICATE_VERIFY_FAILED] certificate verify failed:
[nltk_data]     unable to get local issuer certificate (_ssl.c:997)>


In [2]:
dataset = pd.read_csv('dataset/dataset_komentar_instagram_cyberbullying.csv')
dataset

Id Sentiment                             Instagram Comment Text
0      1  negative   <USERNAME> TOLOL!! Gak ada hubungan nya kegug...
1      2  negative  Geblek lo tata...cowo bgt dibela2in balikan......
2      3  negative  Kmrn termewek2 skr lengket lg duhhh kok labil ...
3      4  negative  Intinya kalau kesel dengan ATT nya, gausah ke ...
4      5  negative  hadewwwww permpuan itu lg!!!!sakit jiwa,knp ha...
..   ...       ...                                                ...
395  396  positive  Bangga sama suami yg selalu ingat istri disela...
396  397  positive  Apaoun pekerjaannya yg penting halal u tuk men...
397  398  positive  Gojek itu mayoritas pegangguran yang lama gak ...
398  399  positive   <USERNAME> aslinya cantik dan ayu loh mbak kr...
399  400  positive   <USERNAME> suami saya seumuran sama saya mba,...

[400 rows x 3 columns]

In [3]:
dt_transformed = dataset[['Sentiment', 'Instagram Comment Text']]
y = dt_transformed.iloc[:, :-1].values
y

array([['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['negative'],
       ['nega

In [4]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
y = np.array(ct.fit_transform(y))

In [5]:
print(y)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 

In [6]:
y_df = pd.DataFrame(y)
y_hate = np.array(y_df[0])
y_offensive = np.array(y_df[1])

In [7]:
print(y_hate)
print(y_offensive)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [8]:
corpus = []
for i in range (0, 400):
    review = re.sub("[^a-zA-Z]", ' ', dt_transformed['Instagram Comment Text'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    all_stopwords = stopwords.words('indonesian')
    review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
    review = ' '.join(review)
    corpus.append(review)

In [55]:
cv = CountVectorizer(max_features = 2000)
x = cv.fit_transform(corpus).toarray()

In [56]:
x_train, x_test, y_train, y_test = train_test_split(x, y_hate, test_size = 0.2, random_state = 0)

In [57]:
classifier_rf = RandomForestClassifier()
classifier_rf.fit(x_train, y_train)

RandomForestClassifier()

In [58]:
classifier_np = GaussianNB()
classifier_np.fit(x_train, y_train)

GaussianNB()

In [59]:
classifier_lr = LogisticRegression(random_state = 0)
classifier_lr.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [60]:
classifier_svm = svm.SVC()
classifier_svm.fit(x_train, y_train)

SVC()

In [61]:
from sklearn.metrics import confusion_matrix
y_pred_rf = classifier_rf.predict(x_test)
cm = confusion_matrix(y_test, y_pred_rf)
print(cm)

[[30  4]
 [14 32]]


In [62]:
y_pred_np = classifier_np.predict(x_test)
cm = confusion_matrix(y_test, y_pred_np)
print(cm)

[[27  7]
 [ 6 40]]


In [63]:
y_pred_svm = classifier_svm.predict(x_test)
cm = confusion_matrix(y_test, y_pred_svm)
print(cm)

[[27  7]
 [ 9 37]]


In [64]:
y_pred_lr = classifier_lr.predict(x_test)
cm = confusion_matrix(y_test, y_pred_lr)
print(cm)

[[29  5]
 [ 9 37]]


In [65]:
from sklearn.metrics import accuracy_score
rf_score = accuracy_score(y_test, y_pred_rf)
svm_score = accuracy_score(y_test, y_pred_svm)
lr_score = accuracy_score(y_test, y_pred_lr)
np_score = accuracy_score(y_test, y_pred_np)

print('Random Forest Accuracy:', str(rf_score))
print('Support Vector Machine Accuracy:', str(svm_score))
print('Logistic Regression Accuracy:', str(lr_score))
print('Naive Bayes Accuracy:', str(np_score))

Random Forest Accuracy: 0.775
Support Vector Machine Accuracy: 0.8
Logistic Regression Accuracy: 0.825
Naive Bayes Accuracy: 0.8375


In [70]:
import pickle
filename = 'model_Bayes.pkl'
pickle.dump(classifier_np, open(filename, 'wb'))

In [71]:
import pickle
filename = 'feature.pkl'
pickle.dump(cv, open(filename, 'wb'))